### ISSUE TITLE
Timestamp DateTime.Kind Unspecified

### ISSUE THREAD

**Issue by PaulRReynolds** [giometrix/TableStorage.Abstractions.POCO#11]
Firstly, I want to say thanks for a great library. We're using it very successfully as a wrapper around Azure Table Storage and it's making life a lot easier!

I've noticed something about the Timestamp property being automatically hydrated from the table record timestamp. The property is being successfully populated, however when I use a `DateTime` property to do this, the `Kind` is being returned as `Unspecified` with a local time. Since the timestamp within Table Storage is stored in UTC, it would be useful to specify this on the Timestamp DateTime object to avoid the potential for ambiguity in callers. Using DateTimeOffset does set the correct offset value.

I'd be happy to raise a PR to implement this if you can point me in the right direction for where this is populated since I don't see it.

Thanks again,

Paul

**Comment by giometrix** [comment]
@PaulRReynolds fixed in 3.0.1
