### ISSUE TITLE
Great project, one addition however would make it even better

### ISSUE THREAD

**Issue by gpalsson** [giometrix/TableStorage.Abstractions.POCO#2]
Add to store:
public async Task InsertOrReplaceAsync(T record)
        {
            if (record == null)
            {
                throw new ArgumentNullException(nameof(record));
            }

            var operation = TableOperation.InsertOrReplace(record);

            await _cloudTable.ExecuteAsync(operation).ConfigureAwait(false);
        }
For those situations where you don't want to query to figure out if you already have the entity stored but want to update timestamp no matter what (for example if you do web scraping).

**Comment by gpalsson** [comment]
If you are interested I have made the necessary changes to  
TableStorage.Abstractions.Store ITableStore and TableStore 
along with 
TableStorage.Abstractions.POCO IPocoTableStore and PocoTableStore

I just don't know how to send it or update it to make it available for everyone.
Until then ill just use my private package with the updated methods.

**Comment by giometrix** [comment]
Sorry didn’t see this.  Care to make a pull request ?

**Comment by giometrix** [comment]
My library depends on TableStorage.Abstractions.  I have already submitted a pull request with the additional functionality ( https://github.com/Tazmainiandevil/TableStorage.Abstractions/pull/8 ), once it gets approved I will update my library and create a new nuget package.

**Comment by giometrix** [comment]
InsertOrReplace has been added and available on nuget in 2.1.0
