### ISSUE TITLE
GetAllRecordsPagedAsync seems to return same results over and over again

### ISSUE THREAD

**Issue by gpalsson** [giometrix/TableStorage.Abstractions.POCO#3]
GetAllRecordsPaged (not async) seems to work however.

It seems to stem from TableStorage.Abstractions.Store.

**Comment by giometrix** [comment]
Thanks for the bug report.  I have fixed the issue in TableStorage.Abstractions and have submitted a PR.

In the meantime I have a direct reference to the fixed library in this project.  Version 2.2 on nuget contains the fix.
